//! GCC (Google Congestion Control) sender-side bandwidth estimator.
//!
//! Reads TWCC feedback packets generated by the remote [`TwccReceiverInterceptor`] and
//! estimates available send bandwidth using a trendline delay filter and AIMD rate
//! controller, following RFC 8698 / draft-ietf-rmcat-gcc-02.
//!
//! # Chain position
//!
//! GCC must be **inner** to [`TwccSenderInterceptor`] so that `handle_write` sees
//! packets after the TWCC sequence number has already been stamped.
//! Add GCC first (innermost), then TwccSender:
//!
//! ```text
//! Registry::new()
//!     .with(gcc_builder.build())          // inner
//!     .with(TwccSenderBuilder::new()...)  // outer — stamps TWCC seq, then calls GCC
//! ```
//!
//! `handle_write` flows outer → inner: TwccSender stamps first, then GCC reads it.
//! `handle_read` (TWCC feedback) also flows outer → inner: TwccSender passes through,
//! then GCC processes the feedback.
//!
//! # Usage
//!
//! ```ignore
//! use rtc_interceptor::{Registry, TwccSenderBuilder, GccInterceptorBuilder};
//!
//! let (gcc_builder, gcc_handle) = GccInterceptorBuilder::new();
//! let chain = Registry::new()
//!     .with(gcc_builder.build())              // GCC inner
//!     .with(TwccSenderBuilder::new().build()) // TwccSender outer
//!     .build();
//!
//! // In the application polling loop:
//! if let Some(bps) = gcc_handle.target_bitrate_bps() {
//!     encoder.set_bitrate(bps);
//! }
//! ```
//!
//! [`TwccSenderInterceptor`]: crate::TwccSenderInterceptor
//! [`TwccReceiverInterceptor`]: crate::TwccReceiverInterceptor

mod rate_controller;
mod trendline;

use crate::stream_info::StreamInfo;
use crate::{Interceptor, Packet, TaggedPacket, interceptor};
use log::trace;
use rate_controller::AimdRateController;
use rtcp::transport_feedbacks::transport_layer_cc::{
    PacketStatusChunk, SymbolTypeTcc, TransportLayerCc,
};
use rtp::extension::transport_cc_extension::TransportCcExtension;
use shared::error::Error;
use shared::marshal::Unmarshal;
use std::collections::HashMap;
use std::marker::PhantomData;
use std::sync::{Arc, Mutex};
use std::time::Instant;
use trendline::TrendlineFilter;

/// Shared state written by [`GccInterceptor`] and read by [`GccHandle`].
pub struct GccShared {
    /// Latest estimated available send bandwidth, in bits per second.
    /// `None` until the first TWCC feedback has been processed.
    pub target_bitrate_bps: Option<u32>,
}

/// Read-only handle to the latest GCC bandwidth estimate.
///
/// Clone-able and thread-safe — share freely across application threads.
#[derive(Clone)]
pub struct GccHandle {
    inner: Arc<Mutex<GccShared>>,
}

impl GccHandle {
    /// Returns the latest estimated available send bandwidth in bps, or `None`
    /// if no TWCC feedback has been processed yet.
    pub fn target_bitrate_bps(&self) -> Option<u32> {
        self.inner
            .lock()
            .unwrap_or_else(|e| {
                log::warn!("gcc: shared mutex poisoned, recovering last estimate");
                e.into_inner()
            })
            .target_bitrate_bps
    }
}

/// Builder for [`GccInterceptor`].
///
/// Create with [`GccInterceptorBuilder::new`], which returns `(builder, handle)`.
pub struct GccInterceptorBuilder<P> {
    min_bitrate_bps: u32,
    max_bitrate_bps: u32,
    shared: Arc<Mutex<GccShared>>,
    _phantom: PhantomData<P>,
}

impl<P> GccInterceptorBuilder<P> {
    /// Create a new builder and the associated [`GccHandle`].
    ///
    /// The handle can be shared with the application so it can read the
    /// latest bitrate estimate each polling tick.
    pub fn new() -> (Self, GccHandle) {
        let shared = Arc::new(Mutex::new(GccShared {
            target_bitrate_bps: None,
        }));
        let handle = GccHandle {
            inner: shared.clone(),
        };
        let builder = Self {
            min_bitrate_bps: 30_000,
            max_bitrate_bps: 2_500_000,
            shared,
            _phantom: PhantomData,
        };
        (builder, handle)
    }

    /// Minimum send rate floor (default 30 kbps).
    pub fn with_min_bitrate(mut self, bps: u32) -> Self {
        self.min_bitrate_bps = bps;
        self
    }

    /// Maximum send rate ceiling (default 2.5 Mbps).
    pub fn with_max_bitrate(mut self, bps: u32) -> Self {
        self.max_bitrate_bps = bps;
        self
    }

    /// Build the interceptor factory closure.
    pub fn build(self) -> impl FnOnce(P) -> GccInterceptor<P> {
        move |inner| GccInterceptor {
            inner,
            local_streams: HashMap::new(),
            send_times: HashMap::new(),
            start_time: Instant::now(),
            trendline: TrendlineFilter::new(),
            rate_controller: AimdRateController::new(
                self.min_bitrate_bps as f64,
                self.max_bitrate_bps as f64,
            ),
            shared: self.shared,
        }
    }
}

/// Sender-side GCC bandwidth estimator interceptor.
///
/// Intercepts outgoing RTP to record send-times (keyed by TWCC transport-wide
/// sequence number), then processes incoming TWCC feedback RTCP packets to
/// update the trendline delay filter and AIMD rate controller.  The resulting
/// bitrate estimate is written to the [`GccHandle`] shared state.
#[derive(Interceptor)]
pub struct GccInterceptor<P> {
    #[next]
    inner: P,

    /// SSRC → TWCC header extension ID, populated in `bind_local_stream`.
    local_streams: HashMap<u32, u8>,

    /// Send-time log: transport-wide seq → send_time_ms_from_start.
    ///
    /// Ring-buffer semantics: entries more than 512 sequence numbers behind the
    /// current head are pruned to bound memory usage.
    send_times: HashMap<u16, f64>,

    /// Monotonic baseline for converting `Instant` values to milliseconds.
    start_time: Instant,

    trendline: TrendlineFilter,
    rate_controller: AimdRateController,

    /// Shared state — written here, read via [`GccHandle`].
    shared: Arc<Mutex<GccShared>>,
}

#[interceptor]
impl<P: Interceptor> GccInterceptor<P> {
    /// Snoop on outgoing RTP: record send_time_ms keyed by TWCC seq.
    ///
    /// Must be inner to [`TwccSenderInterceptor`] so the sequence number has
    /// already been stamped by the time this method is called.
    #[overrides]
    fn handle_write(&mut self, msg: TaggedPacket) -> Result<(), Self::Error> {
        if let Packet::Rtp(ref rtp) = msg.message
            && let Some(&ext_id) = self.local_streams.get(&rtp.header.ssrc)
            && let Some(ext_bytes) = rtp.header.get_extension(ext_id)
        {
            let mut buf = ext_bytes.clone();
            if let Ok(tcc_ext) = TransportCcExtension::unmarshal(&mut buf) {
                let seq = tcc_ext.transport_sequence;
                let send_ms = msg.now.duration_since(self.start_time).as_secs_f64() * 1000.0;
                self.send_times.insert(seq, send_ms);

                // Prune entries > 512 sequence numbers behind the current head.
                if self.send_times.len() > 512 {
                    self.send_times.retain(|&s, _| seq.wrapping_sub(s) <= 512);
                }
            }
        }
        self.inner.handle_write(msg)
    }

    /// Intercept incoming TWCC feedback RTCP and update the bandwidth estimate.
    #[overrides]
    fn handle_read(&mut self, msg: TaggedPacket) -> Result<(), Self::Error> {
        if let Packet::Rtcp(ref rtcp_pkts) = msg.message {
            let now = msg.now;
            for fb in rtcp_pkts
                .iter()
                .filter_map(|pkt| pkt.as_any().downcast_ref::<TransportLayerCc>())
            {
                self.process_feedback(fb, now);
            }
        }
        self.inner.handle_read(msg)
    }

    /// Register a local stream and record its TWCC extension ID.
    #[overrides]
    fn bind_local_stream(&mut self, info: &StreamInfo) {
        use crate::twcc::stream_supports_twcc;
        if let Some(ext_id) = stream_supports_twcc(info)
            && ext_id != 0
        {
            self.local_streams.insert(info.ssrc, ext_id);
        }
        self.inner.bind_local_stream(info);
    }

    /// Remove a local stream.
    #[overrides]
    fn unbind_local_stream(&mut self, info: &StreamInfo) {
        self.local_streams.remove(&info.ssrc);
        self.inner.unbind_local_stream(info);
    }
}

impl<P: Interceptor> GccInterceptor<P> {
    /// Process one TWCC feedback packet: reconstruct timing pairs, update
    /// trendline + rate controller, publish new estimate to shared state.
    fn process_feedback(&mut self, fb: &TransportLayerCc, now: Instant) {
        let pairs = self.extract_send_recv_pairs(fb);
        if pairs.is_empty() {
            return;
        }

        let loss = loss_fraction(fb);

        for (send_ms, recv_ms) in pairs {
            self.trendline.update(send_ms, recv_ms);
        }

        let signal = self.trendline.signal();
        let estimate = self.rate_controller.update(signal, loss, now);

        trace!(
            "gcc: signal={:?} loss={:.1}% estimate={:.0}bps",
            signal,
            loss * 100.0,
            estimate
        );

        self.shared
            .lock()
            .unwrap_or_else(|e| {
                log::warn!("gcc: shared mutex poisoned, recovering to publish estimate");
                e.into_inner()
            })
            .target_bitrate_bps = Some(estimate as u32);
    }

    /// Reconstruct `(send_time_ms, recv_time_ms)` pairs from a TWCC feedback packet.
    ///
    /// Only packets that are in the local `send_times` log AND were marked as
    /// received in the feedback are included.
    fn extract_send_recv_pairs(&self, fb: &TransportLayerCc) -> Vec<(f64, f64)> {
        // Base receive time: reference_time is 24-bit in 64 ms units → microseconds.
        let base_recv_us = (fb.reference_time as i64) * 64_000;
        let mut recv_us = base_recv_us;
        let mut delta_idx = 0usize;
        let mut seq = fb.base_sequence_number;
        let mut result = Vec::new();

        for chunk in &fb.packet_chunks {
            // Iterate chunk contents inline to avoid allocating a Vec per chunk.
            match chunk {
                PacketStatusChunk::RunLengthChunk(rlc) => {
                    for _ in 0..rlc.run_length {
                        self.process_status(
                            rlc.packet_status_symbol,
                            fb,
                            &mut recv_us,
                            &mut delta_idx,
                            seq,
                            &mut result,
                        );
                        seq = seq.wrapping_add(1);
                    }
                }
                PacketStatusChunk::StatusVectorChunk(svc) => {
                    for &status in &svc.symbol_list {
                        self.process_status(
                            status,
                            fb,
                            &mut recv_us,
                            &mut delta_idx,
                            seq,
                            &mut result,
                        );
                        seq = seq.wrapping_add(1);
                    }
                }
            }
        }

        result
    }

    /// Helper: process one packet status symbol during send/recv pair extraction.
    #[inline]
    fn process_status(
        &self,
        status: SymbolTypeTcc,
        fb: &TransportLayerCc,
        recv_us: &mut i64,
        delta_idx: &mut usize,
        seq: u16,
        result: &mut Vec<(f64, f64)>,
    ) {
        if matches!(
            status,
            SymbolTypeTcc::PacketReceivedSmallDelta | SymbolTypeTcc::PacketReceivedLargeDelta
        ) && *delta_idx < fb.recv_deltas.len()
        {
            *recv_us += fb.recv_deltas[*delta_idx].delta;
            *delta_idx += 1;

            if let Some(&send_ms) = self.send_times.get(&seq) {
                let recv_ms = *recv_us as f64 / 1000.0;
                result.push((send_ms, recv_ms));
            }
        }
    }
}

/// Compute the fraction of packets not received in a TWCC feedback packet.
fn loss_fraction(fb: &TransportLayerCc) -> f64 {
    let mut total = 0u32;
    let mut received = 0u32;

    for chunk in &fb.packet_chunks {
        match chunk {
            PacketStatusChunk::RunLengthChunk(rlc) => {
                total += rlc.run_length as u32;
                if rlc.packet_status_symbol != SymbolTypeTcc::PacketNotReceived {
                    received += rlc.run_length as u32;
                }
            }
            PacketStatusChunk::StatusVectorChunk(svc) => {
                for sym in &svc.symbol_list {
                    total += 1;
                    if *sym != SymbolTypeTcc::PacketNotReceived {
                        received += 1;
                    }
                }
            }
        }
    }

    if total == 0 {
        0.0
    } else {
        1.0 - received as f64 / total as f64
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{RTPHeaderExtension, Registry, twcc::TRANSPORT_CC_URI};
    use rtcp::transport_feedbacks::transport_layer_cc::{
        RecvDelta, RunLengthChunk, StatusChunkTypeTcc, TYPE_TCC_DELTA_SCALE_FACTOR,
    };
    use sansio::Protocol;
    use shared::{TransportContext, TransportMessage};
    use std::time::Duration;

    fn stream_info_with_twcc(ssrc: u32) -> StreamInfo {
        StreamInfo {
            ssrc,
            rtp_header_extensions: vec![RTPHeaderExtension {
                uri: TRANSPORT_CC_URI.to_string(),
                id: 5,
            }],
            ..Default::default()
        }
    }

    fn make_rtp(ssrc: u32, rtp_seq: u16, now: Instant) -> TaggedPacket {
        TransportMessage {
            now,
            transport: TransportContext::default(),
            message: Packet::Rtp(rtp::Packet {
                header: rtp::header::Header {
                    ssrc,
                    sequence_number: rtp_seq,
                    ..Default::default()
                },
                ..Default::default()
            }),
        }
    }

    fn make_twcc_feedback(
        base_seq: u16,
        recv_times_us: &[i64], // per-packet receive times in microseconds (absolute)
        now: Instant,
    ) -> TaggedPacket {
        let base_recv_us = recv_times_us.first().copied().unwrap_or(0);
        // reference_time is 24-bit in 64ms units.
        let reference_time = (base_recv_us / 64_000) as u32;
        let base_ref_us = reference_time as i64 * 64_000;

        let mut deltas = Vec::new();
        let mut prev_us = base_ref_us;
        for &t in recv_times_us {
            let delta_us = t - prev_us;
            deltas.push(RecvDelta {
                type_tcc_packet: SymbolTypeTcc::PacketReceivedSmallDelta,
                delta: delta_us,
            });
            prev_us = t;
        }

        let chunk = PacketStatusChunk::RunLengthChunk(RunLengthChunk {
            type_tcc: StatusChunkTypeTcc::RunLengthChunk,
            packet_status_symbol: SymbolTypeTcc::PacketReceivedSmallDelta,
            run_length: recv_times_us.len() as u16,
        });

        let fb = TransportLayerCc {
            sender_ssrc: 0,
            media_ssrc: 0,
            base_sequence_number: base_seq,
            packet_status_count: recv_times_us.len() as u16,
            reference_time,
            fb_pkt_count: 0,
            packet_chunks: vec![chunk],
            recv_deltas: deltas,
        };

        TransportMessage {
            now,
            transport: TransportContext::default(),
            message: Packet::Rtcp(vec![Box::new(fb)]),
        }
    }

    /// Build a chain with TwccSender (outer) → GccInterceptor (inner).
    ///
    /// GCC must be inner so `handle_write` sees TWCC-stamped packets.
    fn make_chain() -> (
        impl Protocol<TaggedPacket, TaggedPacket, ()> + crate::Interceptor,
        GccHandle,
    ) {
        use crate::TwccSenderBuilder;
        let (gcc_builder, handle) = GccInterceptorBuilder::new();
        let chain = Registry::new()
            .with(gcc_builder.build()) // GCC inner
            .with(TwccSenderBuilder::new().build()) // TwccSender outer
            .build();
        (chain, handle)
    }

    #[test]
    fn test_handle_returns_estimate_after_feedback() {
        let (mut chain, handle) = make_chain();
        let ssrc = 1001u32;
        chain.bind_local_stream(&stream_info_with_twcc(ssrc));

        let base = Instant::now();
        // Send 5 packets; TwccSender will stamp seq 0..4.
        for i in 0..5u16 {
            chain
                .handle_write(make_rtp(
                    ssrc,
                    i,
                    base + Duration::from_millis(i as u64 * 33),
                ))
                .unwrap();
        }

        // Feed back receive times: 33ms inter-packet spacing, 20ms constant one-way delay.
        // Units: microseconds.  20ms = 20_000µs; spacing 33ms = 33_000µs.
        let recv_us: Vec<i64> = (0..5).map(|i: i64| i * 33_000 + 20_000).collect();

        chain
            .handle_read(make_twcc_feedback(
                0,
                &recv_us,
                base + Duration::from_millis(200),
            ))
            .unwrap();

        assert!(
            handle.target_bitrate_bps().is_some(),
            "should have an estimate after feedback"
        );
    }

    #[test]
    fn test_no_estimate_before_feedback() {
        let (mut chain, handle) = make_chain();
        let ssrc = 2001u32;
        chain.bind_local_stream(&stream_info_with_twcc(ssrc));
        chain
            .handle_write(make_rtp(ssrc, 0, Instant::now()))
            .unwrap();
        // No feedback yet.
        assert!(handle.target_bitrate_bps().is_none());
    }

    #[test]
    fn test_non_twcc_rtcp_passes_through() {
        let (mut chain, handle) = make_chain();
        let rtcp_pkt = TransportMessage {
            now: Instant::now(),
            transport: TransportContext::default(),
            message: Packet::Rtcp(vec![Box::new(rtcp::receiver_report::ReceiverReport {
                ssrc: 42,
                ..Default::default()
            })]),
        };
        // Should not panic; non-TWCC RTCP is forwarded.
        chain.handle_read(rtcp_pkt).unwrap();
        assert!(handle.target_bitrate_bps().is_none());
    }

    #[test]
    fn test_unbind_removes_stream() {
        let (mut chain, _handle) = make_chain();
        let ssrc = 3001u32;
        let info = stream_info_with_twcc(ssrc);
        chain.bind_local_stream(&info);
        chain.unbind_remote_stream(&info); // unbind (remote stream - no-op here)
        chain.unbind_local_stream(&info);
        // No panic — stream was removed cleanly.
    }

    #[test]
    fn test_send_time_not_recorded_without_twcc_ext() {
        // RTP sent on an SSRC not bound with TWCC should not populate send_times.
        let (mut chain, _handle) = make_chain();
        let ssrc = 4001u32;
        // Bind WITHOUT TWCC ext.
        let info = StreamInfo {
            ssrc,
            rtp_header_extensions: vec![],
            ..Default::default()
        };
        chain.bind_local_stream(&info);
        // Just verify no panic and no estimate without TWCC feedback.
        chain
            .handle_write(make_rtp(ssrc, 1, Instant::now()))
            .unwrap();
    }

    #[test]
    fn test_loss_fraction_all_received() {
        let chunk = PacketStatusChunk::RunLengthChunk(RunLengthChunk {
            type_tcc: StatusChunkTypeTcc::RunLengthChunk,
            packet_status_symbol: SymbolTypeTcc::PacketReceivedSmallDelta,
            run_length: 10,
        });
        let fb = TransportLayerCc {
            packet_chunks: vec![chunk],
            recv_deltas: (0..10)
                .map(|_| RecvDelta {
                    type_tcc_packet: SymbolTypeTcc::PacketReceivedSmallDelta,
                    delta: 33_000 * TYPE_TCC_DELTA_SCALE_FACTOR,
                })
                .collect(),
            ..Default::default()
        };
        assert_eq!(loss_fraction(&fb), 0.0);
    }

    #[test]
    fn test_loss_fraction_empty_chunks() {
        let fb = TransportLayerCc {
            packet_chunks: vec![],
            ..Default::default()
        };
        assert_eq!(loss_fraction(&fb), 0.0);
    }

    #[test]
    fn test_loss_fraction_status_vector_mixed() {
        use rtcp::transport_feedbacks::transport_layer_cc::{StatusVectorChunk, SymbolSizeTypeTcc};
        // 3 received + 2 lost = 60% received, 40% loss.
        let chunk = PacketStatusChunk::StatusVectorChunk(StatusVectorChunk {
            type_tcc: StatusChunkTypeTcc::StatusVectorChunk,
            symbol_size: SymbolSizeTypeTcc::TwoBit,
            symbol_list: vec![
                SymbolTypeTcc::PacketReceivedSmallDelta,
                SymbolTypeTcc::PacketNotReceived,
                SymbolTypeTcc::PacketReceivedLargeDelta,
                SymbolTypeTcc::PacketNotReceived,
                SymbolTypeTcc::PacketReceivedSmallDelta,
            ],
        });
        let fb = TransportLayerCc {
            packet_chunks: vec![chunk],
            recv_deltas: vec![
                RecvDelta {
                    type_tcc_packet: SymbolTypeTcc::PacketReceivedSmallDelta,
                    delta: 10_000,
                },
                RecvDelta {
                    type_tcc_packet: SymbolTypeTcc::PacketReceivedLargeDelta,
                    delta: 20_000,
                },
                RecvDelta {
                    type_tcc_packet: SymbolTypeTcc::PacketReceivedSmallDelta,
                    delta: 10_000,
                },
            ],
            ..Default::default()
        };
        let loss = loss_fraction(&fb);
        assert!((loss - 0.4).abs() < 1e-9, "expected 40% loss, got {loss}");
    }

    #[test]
    fn test_builder_custom_bitrate_bounds() {
        let (builder, _handle) = GccInterceptorBuilder::<()>::new();
        let builder = builder
            .with_min_bitrate(100_000)
            .with_max_bitrate(5_000_000);
        assert_eq!(builder.min_bitrate_bps, 100_000);
        assert_eq!(builder.max_bitrate_bps, 5_000_000);
    }

    #[test]
    fn test_gcc_handle_clone_shares_state() {
        let (_builder, handle) = GccInterceptorBuilder::<()>::new();
        let handle2 = handle.clone();
        assert!(handle.target_bitrate_bps().is_none());
        assert!(handle2.target_bitrate_bps().is_none());
        // Write through the shared mutex.
        handle.inner.lock().unwrap().target_bitrate_bps = Some(500_000);
        assert_eq!(handle2.target_bitrate_bps(), Some(500_000));
    }

    #[test]
    fn test_loss_fraction_all_lost() {
        let chunk = PacketStatusChunk::RunLengthChunk(RunLengthChunk {
            type_tcc: StatusChunkTypeTcc::RunLengthChunk,
            packet_status_symbol: SymbolTypeTcc::PacketNotReceived,
            run_length: 5,
        });
        let fb = TransportLayerCc {
            packet_chunks: vec![chunk],
            ..Default::default()
        };
        assert_eq!(loss_fraction(&fb), 1.0);
    }
}
