[package]
name = "rtc-shared"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "RTC Shared in Rust"
license.workspace = true
documentation = "https://docs.rs/rtc-shared"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["ifaces", "marshal", "replay"]
ifaces = []
marshal = []
replay = []

[dependencies]
thiserror.workspace = true
substring.workspace = true
bytes.workspace = true
url.workspace = true
rcgen.workspace = true
sec1.workspace = true
p256.workspace = true
aes.workspace = true
aes-gcm.workspace = true
rand.workspace = true
serde.workspace = true

[target.'cfg(not(windows))'.dependencies]
nix = "0.26.2"

[target.'cfg(windows)'.dependencies]
bitflags = "1.3"
winapi = { version = "0.3.9", features = [
    "basetsd",
    "guiddef",
    "ws2def",
    "winerror",
    "ws2ipdef",
] }
