[package]
name = "rtc-stun"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "RTC STUN in Rust"
license.workspace = true
documentation = "https://docs.rs/rtc-stun"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["ring"]
ring = ["crypto/ring"]
aws-lc-rs = ["crypto/aws-lc-rs"]
bench = []

[dependencies]
shared = { workspace = true, default-features = false, features = [] }
sansio.workspace = true
crypto.workspace = true

bytes.workspace = true
lazy_static.workspace = true
url.workspace = true
rand.workspace = true
base64.workspace = true
crc.workspace = true

[dev-dependencies]
clap.workspace = true
criterion.workspace = true

[[bench]]
name = "bench"
harness = false

[[example]]
name = "stun_client"
path = "examples/stun_client.rs"
bench = false

[[example]]
name = "stun_decode"
path = "examples/stun_decode.rs"
bench = false
